---
title: "Graphics with ggplot2"
author: 'bbobango'
output: html_document
date: '24.01.2021'
---

# Learning ggplot2

We are learning ggplot2 and it's going to be amazing.

```{r, echo=FALSE}
library(tidyverse)

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```
```{r}
ggplot(data = se) +
    geom_point(aes(x = year, y = visitors/1000000, color = state)) +
    labs( x = 'Year', y = 'Visitors in millions', title = 'Park Visitation') +
    theme_light(base_size = 10) +
    theme(legend.title = element_blank(), 
          axis.text.x = element_text(angle = 45, hjust = 1, size = 6)) +
    scale_x_continuous(n.breaks = 50) + scale_y_continuous(n.breaks = 20)
```

